kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: argo-portal
  namespace: opendatahub
spec:
  to:
    kind: Service
    name: argo-server
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
  port:
    targetPort: 2746
