apiVersion: v1
kind: ConfigMap
data:
  config: |
    containerRuntimeExecutor: "k8sapi"
    # SSO Configuration for the Argo server.
    # You must also start argo server with `--auth-mode sso`.
    # https://argoproj.github.io/argo/argo-server-auth-mode/
    sso:
      # This is the root URL of the OIDC provider (required).
      issuer: https://issuer.root.url/
      # This is name of the secret and the key in it that contain OIDC client
      # ID issued to the application by the provider (required).
      clientId:
        name: client-id-secret
        key: client-id-key
      # This is name of the secret and the key in it that contain OIDC client
      # secret issued to the application by the provider (required).
      clientSecret:
        name: client-secret-secret
        key: client-secret-key
      # This is the redirect URL supplied to the provider (required). It must
      # be in the form <argo-server-root-url>/oauth2/callback. It must be
      # browser-accessible.
      redirectUrl: https://argo-server/oauth2/callback
metadata:
  name: workflow-controller-configmap
